/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary":                    "#000b1f",
        "primary-container":          "#0a2240",
        "primary-fixed":              "#d5e3ff",
        "primary-fixed-dim":          "#b2c7ee",
        "on-primary":                 "#ffffff",
        "on-primary-fixed":           "#031c39",
        "on-primary-fixed-variant":   "#334767",
        "on-primary-container":       "#758aad",
        "secondary":                  "#835500",
        "secondary-container":        "#feae2c",
        "secondary-fixed":            "#ffddb4",
        "secondary-fixed-dim":        "#ffb955",
        "on-secondary":               "#ffffff",
        "on-secondary-fixed":         "#291800",
        "on-secondary-fixed-variant": "#633f00",
        "on-secondary-container":     "#6b4500",
        "tertiary":                   "#170700",
        "tertiary-container":         "#381a00",
        "tertiary-fixed":             "#ffdcc3",
        "tertiary-fixed-dim":         "#f3bb91",
        "on-tertiary":                "#ffffff",
        "on-tertiary-fixed":          "#2f1500",
        "on-tertiary-fixed-variant":  "#643e1d",
        "error":                      "#ba1a1a",
        "error-container":            "#ffdad6",
        "on-error":                   "#ffffff",
        "on-error-container":         "#93000a",
        "surface":                    "#fcf9f8",
        "surface-dim":                "#dcd9d9",
        "surface-bright":             "#fcf9f8",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f6f3f2",
        "surface-container":          "#f0eded",
        "surface-container-high":     "#eae7e7",
        "surface-container-highest":  "#e5e2e1",
        "surface-tint":               "#4b5f80",
        "surface-variant":            "#e5e2e1",
        "on-surface":                 "#1c1b1b",
        "on-surface-variant":         "#44474e",
        "background":                 "#fcf9f8",
        "on-background":              "#1c1b1b",
        "outline":                    "#74777e",
        "outline-variant":            "#c4c6ce",
        "inverse-surface":            "#313030",
        "inverse-on-surface":         "#f3f0ef",
        "inverse-primary":            "#b2c7ee",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        full:    "0.75rem",
      },
      spacing: {
        "container-max":  "1280px",
        "stack-lg":       "48px",
        "stack-md":       "24px",
        "stack-sm":       "12px",
        "stack-xs":       "4px",
        "base":           "8px",
        "gutter":         "24px",
        "margin-desktop": "40px",
        "margin-mobile":  "16px",
      },
      fontFamily: {
        "headline-xl":       ["Work Sans", "sans-serif"],
        "headline-lg":       ["Work Sans", "sans-serif"],
        "headline-lg-mobile":["Work Sans", "sans-serif"],
        "headline-md":       ["Work Sans", "sans-serif"],
        "body-lg":           ["Inter", "sans-serif"],
        "body-md":           ["Inter", "sans-serif"],
        "body-sm":           ["Inter", "sans-serif"],
        "label-caps":        ["Inter", "sans-serif"],
        "data-mono":         ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-xl":        ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg":        ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md":        ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg":            ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md":            ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm":            ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps":         ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "data-mono":          ["14px", { lineHeight: "20px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};